title: A byte of China
description: "Hi, I am Ian Hom. There are only two things I don't know about C: this and that."
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
